author: JiangChunbo # 作者
description: JiangChunbo's blog
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
 Home: /
 Categories: /categories/
 # Series: /series/
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set utterances, gitment, uyan or disqus
comment: utterances

# utterances config
utterances_repo: JiangChunbo/jiangchunbo.github.io               # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: JiangChunbo
gitment_repo: jiangchunbo.github.io
gitment_oauth_id: 8ff18c626ce6de443832
gitment_oauth_secret: ccbfc51ce15c59b57e0fe4a4dea81060976bbde3

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:
google_analytics:
# disqus config
disqus_shortname:

about:
  banner: ""
  avatar: https://avatars.githubusercontent.com/u/50109770?s=96&v=4
  description: "The end is always near."
  # weibo_username: yanm1ng
  # twitter_username: yanm1ng
  # github_username: yanm1ng
  # zhihu_username: yummy1121
  # douban_username: yanm1ng
  # linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

# China Registration
# e.g. 京ICP备12345678号-1
icp:
  enable: false
  number: 京ICP备12345678号-1 # e.g. 京ICP备12345678号-1
# e.g. 京公网安备 12345678901234号
ga:
  enable: false
  province: 京           # e.g. 京
  number: 12345678901234 # e.g. 12345678901234




